[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tsrc/lds/qemu-virt.ld', '-Clink-arg=-n', '--cfg=riscv']

[target.riscv64gc-unknown-none-elf]
runner = """\
         qemu-system-riscv64 \
            -machine virt \
            -nographic \
            -bios bootloader/opensbi-qemu.bin \
            -device virtio-blk-device,drive=foo \
            -drive if=none,format=raw,file=fs.img,id=foo \
            -kernel \
         """
