[build]
target = "riscv64gc-unknown-none-elf"
rustflags = ['-Clink-arg=-Tsrc/lds/qemu-virt.ld', '-Clink-arg=-n', '--cfg=riscv']

[target.riscv64gc-unknown-none-elf]
runner = """\
         qemu-system-riscv64 \
            -machine virt \
            -nographic \
            -bios bootloader/rustsbi-qemu.bin \
            -kernel \
         """
